clear;
data = xlsread('Data\data.xlsx');
test_size = 100;
tsize = length(data);
size = tsize - test_size;

% 2nd order
phi_x = [ones(size, 1) data(1:size, 1) data(1:size, 2) data(1:size, 3) data(1:size, 4) ...
                           data(1:size, 1).*data(1:size,1) ...
                           data(1:size, 2).*data(1:size,2) ...
                           data(1:size, 3).*data(1:size,3) ...
                           data(1:size, 4).*data(1:size,4) ...
                           data(1:size, 1).*data(1:size,2) ...
                           data(1:size, 1).*data(1:size,3) ...
                           data(1:size, 1).*data(1:size,4) ...
                           data(1:size, 2).*data(1:size,3) ...
                           data(1:size, 2).*data(1:size,4) ...
                           data(1:size, 3).*data(1:size,4)];
test_x = [ones(test_size, 1) data((tsize-test_size+1):tsize, 1) data((tsize-test_size+1):tsize, 2) data((tsize-test_size+1):tsize, 3) data((tsize-test_size+1):tsize, 4) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,1) ...
                           data((tsize-test_size+1):tsize, 2).*data((tsize-test_size+1):tsize,2) ...
                           data((tsize-test_size+1):tsize, 3).*data((tsize-test_size+1):tsize,3) ...
                           data((tsize-test_size+1):tsize, 4).*data((tsize-test_size+1):tsize,4) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,2) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,3) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,4) ...
                           data((tsize-test_size+1):tsize, 2).*data((tsize-test_size+1):tsize,3) ...
                           data((tsize-test_size+1):tsize, 2).*data((tsize-test_size+1):tsize,4) ...
                           data((tsize-test_size+1):tsize, 3).*data((tsize-test_size+1):tsize,4)];
y = data(1:size, 5);

test_y = data((tsize-test_size+1):tsize, 5);

W = pinv(phi_x)*y;

t = test_x*W;
test_e = sqrt(sum((test_y-t).^2)/tsize);

t = phi_x*W;
train_e = sqrt(sum((y-t).^2)/tsize);


% third order
phi_x_third = [ones(size, 1) data(1:size, 1) data(1:size, 2) data(1:size, 3) data(1:size, 4) ...
                           data(1:size, 1).*data(1:size,1) ...
                           data(1:size, 2).*data(1:size,2) ...
                           data(1:size, 3).*data(1:size,3) ...
                           data(1:size, 4).*data(1:size,4) ...
                           data(1:size, 1).*data(1:size,2) ...
                           data(1:size, 1).*data(1:size,3) ...
                           data(1:size, 1).*data(1:size,4) ...
                           data(1:size, 2).*data(1:size,3) ...
                           data(1:size, 2).*data(1:size,4) ...
                           data(1:size, 3).*data(1:size,4)];
for i = 1:4
    for j = 1:i
        for k = 1:j
            phi_x_third = cat(2, phi_x_third, phi_x_third(:, k+1).*phi_x_third(:, j+1).*phi_x_third(:, i+1));
        end
    end
end
                       
test_x_third = [ones(test_size, 1) data((tsize-test_size+1):tsize, 1) data((tsize-test_size+1):tsize, 2) data((tsize-test_size+1):tsize, 3) data((tsize-test_size+1):tsize, 4) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,1) ...
                           data((tsize-test_size+1):tsize, 2).*data((tsize-test_size+1):tsize,2) ...
                           data((tsize-test_size+1):tsize, 3).*data((tsize-test_size+1):tsize,3) ...
                           data((tsize-test_size+1):tsize, 4).*data((tsize-test_size+1):tsize,4) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,2) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,3) ...
                           data((tsize-test_size+1):tsize, 1).*data((tsize-test_size+1):tsize,4) ...
                           data((tsize-test_size+1):tsize, 2).*data((tsize-test_size+1):tsize,3) ...
                           data((tsize-test_size+1):tsize, 2).*data((tsize-test_size+1):tsize,4) ...
                           data((tsize-test_size+1):tsize, 3).*data((tsize-test_size+1):tsize,4)];

for i = 1:4
    for j = 1:i
        for k = 1:j
            test_x_third = cat(2, test_x_third, test_x_third(:, k+1).*test_x_third(:, j+1).*test_x_third(:, i+1));
        end
    end
end

y_third = data(1:size, 5);

test_y_third = data((tsize-test_size+1):tsize, 5);

W_third = pinv(phi_x_third)*y;

t = test_x_third*W_third;
test_e_third = sqrt(sum((test_y_third-t).^2)/tsize);

t = phi_x_third*W_third;
train_e_third = sqrt(sum((y_third-t).^2)/tsize);